motioneye:
  image: motioneye
  volumes:
    - /mnt/motioneye/media:/media
    - /mnt/motioneye/config:/etc/motioneye
  environment:
    - TIMEZONE="Pacific/Auckland"
  ports:
    - 8081:8081
    - 8765:8765
  restart: always
